config/routes.rb
Rails.application.routes.draw do

  

  get "/users/sign_up" => "users#sign_up"
  post "/users/sign_up" => "users#sign_up"
  
  get "/sessions/sign_in" => "sessions#sign_in"
  post "/sessions/sign_in" => "sessions#create"

  delete "/users/:id" => "sessions#destroy"

  resources :users 

  resources :sessions 
  
  resources :posts do
    resources :comments
  end
 
  root 'users#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end	


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment =
			@post.comments.create(params[:comment].permit(:commenter,
				:body))
			redirect_to post_path(@post)
	end	

	def show
		 @post = Post.find(params[:post_id])
    	@comment = @post.comments.find(params[:id])
    	@comment.destroy
    	redirect_to post_path(@post)
	end	

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
  def index
    @posts = Post.where(:user_id => current_user.id)
  end

  def new
		@post = Post.new
	end	

	def create
		@post = Post.new(params[:posts])
		@post.save

		 if @post.save
    		redirect_to posts_path
  		else
    		render 'new'
 		 end
  	end	
	
	def show
		@post = Post.find(params[:id])
	end

	def edit
  		@post = Post.find(params[:id])
  	end	

	def update 
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :text))
 			redirect_to @post
		else
  		render 'edit'
		end
	end	

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end	

	private
	  def post_params
	    params.require(:post).permit(:title, :text)
	  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index
	end	

	def sign_in
	end	

	def create
		@user = User.find_by(username: params[:username])
		if @user and @user.password = params[:password]
			session[:user_id] = @user.id
			flash[:notice] = "You are logged in"
			redirect_to user_path(@user.id)
		else 	
			flash[:alert] = "You are not logged in. Please try again."
			redirect_to sign_in_path
		end	
	end

	def destroy
		session[:user_id] == nil
		flash[:notice] = "You have logged out"
		redirect_to sessions_sign_in_path	
	end	

	def show
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.all
	end	

	def sign_up
		@user = User.new
	end
	
	def create
		User.create(user_params)

		redirect_to users_path
	end

	def edit
		@user = User.find(params[:id])
				 	
	end

	def update
		@user = User.find(params[:id])
  		@user.update(user_params)

		
		redirect_to users_path

	end		

	def show
		@user = User.find(params[:id])
		@posts = @user.posts

		respond_to do |format|
			format.html
		end	
	end

	private 
	def user_params
		params.require(:user).permit(:fname, :lname, :username, :password, :bday, :email)
	end	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index 
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>snifter</title>
  <link href='https://fonts.googleapis.com/css?family=Oswald|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <meta name="theme-color" content="#ffffff">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
  	<ul>
  		<li class="brdr"><a href="/users/<%= session[:user_id] %>">Profile</a></li>
      <li class="brdr"><a href="/posts">Feed</a></li>
  		<li><a href="/posts/new">New Post</a></li>
  	</ul>
  </nav>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="top-edit-page">
	<div color="hdr">
		<h1>Editing Posts</h1>
	</div>	
	<div class = "edit-page">
		<%= form_for :post, url: post_path(@post), method: :patch do |form| %>
			<% if @post.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
				<ul>
					<% @post.errors.full_message.each do |msg| %>
					<li><%= msg%></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<p>
				<%= form.label :title %><br>
				<%= form.text_field :title %>
			</p>
			<p>
				<%= form.label :text %><br>
				<%= form.text_area :text %>
			</p>
			<p>
				<%= form.submit "Post" %>
			</p>
		<% end %>		
		<%= link_to 'Back', posts_path %>
		</div>
	</div>
</div>	

app/views/posts/index.html.erb
<div class="hdr">
<h1>All Posts</h1>
</div>
<div class="feed">
    <% @posts.each do |post| %>
      <div id="space-me">
      	<h2>Title:</h2>
        		<h3><%= post.title %></h3>
        	<h2>Content:</h2>	
        		<p><%= post.text %></p>
        	<h4><%= link_to 'Show', post_path(post) %>	
        	<%= link_to 'Edit', edit_post_path(post) %>	
        	<%= link_to 'Destroy', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></h4>
      </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<div>
<h1 id="new-header">Make a new post</h1>
</div>
<div class="new-page">
<%= form_for :posts, url: posts_path do |form|%>
	<% if @post.errors.any? %>
   <div id="errorExplanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited
         this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
	<div>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</div>
	<div>
		<%= form.label :text %><br>
		<%= form.text_area :text %>
	</div>
    <%= form.hidden_field :user_id, value: session[:user_id] %>
	<p>
		<%= form.submit "Post" %>
	</p>
<% end %>	
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="header">
  <h1>Posts Page</h1>
</div>

<div class = "posts-page">
<h2>
  <strong>Title:</strong>
  <%= @post.title %>
</h2>
 
<h2>
  <strong>Content:</strong>
  <%= @post.text %>
</h2>

<h2>Add a comment:</h2>
<%= form_for ([@post, @post.comments.build]) do |form| %>
<p>
	<%= form.label :commenter %><br />
	<%= form.text_field :commenter %>
</p>
<p>
	<%=form.label :body %><br />
	<%= form.text_area :body %>
</p>
<p>
	<%= form.submit %>
</p>
<% end %>
<%= link_to 'Back', posts_path %>
| <%= link_to 'Edit', edit_post_path %>

<% if @post.comments.present? %>
  <% @post.comments.each do |comment| %>
  <%= comment.body %>
  <% end %> 
<% end %>  
</div>

app/views/users/edit.html.erb
<div class = "edit-page">
<h1>Edit Users</h1>

<%= form_for @user do |form| %>
	<h2>First name:</h2>
	<h3><%= form.text_field :fname %></h3><br>
	<h2>Last name:</h2>
	<h3><%= form.text_field :lname %></h3><br>
	<h2>Username:</h2>
	<h3><%= form.text_field :username %></h3><br>
	<h2>Password:</h2>
	<h3><%= form.text_field :password %></h3><br>
	<h2>Email:</h2>
	<h3><%= form.text_field :email %></h3><br>
	<%= form.submit %>
<% end %>	

<%= form_tag("/search", method: "get") do %>
	<%= label_tag(:query, "Search") %>
	<%= text_field_tag(:query) %>
	<%= submit_tag("Submit") %>
<% end %>	
</div>

app/views/users/index.html.erb
<div class="unique">
  <h1 id="logo">snifter</h1>  
<div>
  <video autoplay loop id="bgvid">
      <source src="/assets/whiskey.mp4" type="video/mp4">
  </video>
</div>
<div id="sign-in">
  <%= link_to "Sign In", sessions_sign_in_path %>
</div>
<div id="sign-up">
  <%= link_to "Sign Up", users_sign_up_path %>
</div>
</div>

app/views/users/show.html.erb
<div class="show-page">
  <div id="header">   
    <img src="/assets/whisky-bottles.jpg"/>
  <h1 id="welcome">Welcome!</h1>
  </div>

  <div id="profile">
    <h2 class="profile-deets">First name:</h2><p><%= @user.fname %></p>
    <h2 class="profile-deets">Last name:</h2><p><%= @user.lname %></p>
    <h2 class="profile-deets">Username:</h2><p><%= @user.username %></p>
    <h2 class="profile-deets">Email:</h2><p><%= @user.email %></p>  



  <div>
  	<h2><% if @posts.present? %></h2>
  		<h3><% @posts.each do |post| %></h3>
      <h2>Title</h2>
  		<h3><%= post.title %></h3><br />
      <h2>Content</h2>
  		<h3><%= post.text %></h3><br/>
  
  	<h3>	<%= link_to 'Back', posts_path %>
  | <%= link_to 'Edit', edit_post_path %> | <%= link_to 'Destroy', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></h3>
  		<% end %>
  	<% end %>
    <%= link_to "Log Out", session_path(@user.id), method: :delete %>
  </div>
  </div>

  <div>
  
  </div>
</div>

app/views/users/sign_up.html.erb
<div id="whiskey-back">
	<div class="white">
		<h1>Sign Up</h1>

		<%= form_for @user do |form| %>
			<h2>First name:</h2>
			<%= form.text_field :fname %><br>
			<h2>Last name:</h2>
			<%= form.text_field :lname %><br>
			<h2>Username:</h2>
			<%= form.text_field :username %><br>
			<h2>Password:</h2>
			<%= form.text_field :password %><br>
			<h2>Email:</h2>
			<%= form.text_field :email %><br>
			<%= form.submit "Sign Up" %>
		<% end %>
	</div>
</div>